apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: codestatspayingcontainerregistry.azurecr.io/backend-server:runs-locally
        ports:
        - containerPort: 3002 # !!!! not 8000 as previous
        env:
        - name: CASSANDRA_HOST
          value: cassandra-service
        - name: CASSANDRA_PORT
          value: "9042"
        resources:
          requests:
            cpu: "0.5"        # Minimum CPU requested
            memory: "512Mi"   # Minimum memory requested
          limits:
            cpu: "1"          # Maximum CPU allowed
            memory: "1Gi"     # Maximum memory allowed
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002 #!!!!! not 8000
