name: my-inference-env
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - numpy
  - scikit-learn
  - pip:
    - transformers
    - torch
    - pandas
    - pytorch_lightning
    - azureml-defaults
    - requests