$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: local-deployment
endpoint_name: local-endpoint
environment: 
  conda_file: /Users/alinstefanescu/Documents/code-stats/services/inference/environment.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
model:
  path: /Users/alinstefanescu/Documents/code-stats/services/inference/fine_tuned_bert
code_configuration:
    code: /Users/alinstefanescu/Documents/code-stats/services/inference
    scoring_script: cloud_inference.py
instance_type: Standard_DS1_v2
instance_count: 1